name: Go Service Monitor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20 # Use at least Go 1.11 or later

      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 4: Run tests (if applicable)
      - name: Run tests
        run: go test ./...

      # Step 5: Build the application
      - name: Build
        run: go build -o service-monitor .

      # Step 6: Run the application
      - name: Run application
        env:
          CONFIG_FILE: config.json
        run: |
          nohup ./service-monitor &
